name: arrancando
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1-alpha+45

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.4
  json_annotation: ^3.0.0
  flutter_map: ^0.7.3
  latlong: ^0.6.1
  provider: ^3.1.0+1
  flutter_swiper: ^1.1.6
  multi_image_picker: ^4.5.9
  geolocator: ^5.1.4+2
  permission_handler: ^4.0.0
  flare_flutter: ^1.7.1
  image_picker: ^0.6.1+11
  share: ^0.6.3+1
  uni_links: ^0.2.0
  esys_flutter_share: ^1.0.2
  url_launcher: any
  path_provider: any
  file_picker: ^1.4.3+1
  thumbnails: ^1.0.1
  video_thumbnail: ^0.1.6
  video_player: any
  cached_network_image: ^1.1.3
  apple_sign_in: any
  google_sign_in: any
  firebase_analytics: any
  flutter_html: any
  snaplist: any
  icon_shadow: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  flutter_launcher_icons: any

flutter_icons:
  image_path: "./assets/images/icon.png"
  image_path_android: "./assets/images/icon.png"
  image_path_ios: "./assets/images/icon-ios.jpg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flare/fuego.flr
    - assets/flare/logo.flr
    - assets/images/icon.png
    - assets/images/logo-google.png
    - assets/images/logo-facebook.png
    - assets/images/logo-whatsapp.png
    - assets/images/marca.jpg
    - assets/images/icon-no-fire.png
    - assets/images/content/index/plato-filtrar.png
    - assets/images/content/index/plato-personalizar.png
    - assets/images/content/new/cubiertos.png
    - assets/images/content/new/fideos.png
    - assets/images/content/new/tomates.png
    - assets/images/content/new/wok.png
    - assets/images/content/categories/asador.png
    - assets/images/content/categories/bowl.png
    - assets/images/content/categories/wok.png
    - assets/images/content/categories/disco.png
    - assets/images/content/categories/horno.png
    - assets/images/content/categories/olla.png
    - assets/images/content/categories/parrilla.png
    - assets/images/content/categories/plancha.png
    - assets/images/content/categories/sarten.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito_Sans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Black.ttf
          weight: 900
    - family: Monserrat
      fonts:
        - asset: assets/fonts/Monserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Monserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Monserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Monserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Monserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Monserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Monserrat/Montserrat-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Monserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Monserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Monserrat/Montserrat-Thin.ttf
          weight: 100
    - family: ArrancandoIcons
      fonts:
        - asset: assets/fonts/ArrancandoIcons.ttf
          
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
