#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/home/ivan/Programming/Flutter/flutter-sdks/flutter-dev"
export "FLUTTER_APPLICATION_PATH=/home/ivan/MacherIT/Flutter/arrancando"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/home/ivan/Programming/Flutter/flutter-sdks/flutter-dev/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=2.1.4"
export "FLUTTER_BUILD_NUMBER=60"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
