/// Flutter icons ArrancandoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrancandoIcons
///      fonts:
///       - asset: fonts/ArrancandoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArrancandoIcons {
  ArrancandoIcons._();

  static const _kFontFam = 'ArrancandoIcons';
  static const _kFontPkg = null;

  static const IconData reloj = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dificultad = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
