# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Deployar bundle como beta'
  lane :beta do
    # gradle(task: 'clean assembleRelease')
    # crashlytics
    # gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
			skip_upload_images: true,
      skip_upload_screenshots: true,
			skip_upload_changelogs: true,
      skip_upload_metadata: true
    )
  end

	desc 'Deployar bundle como alpha'
  lane :alpha do
    # gradle(task: 'clean assembleRelease')
    # crashlytics
    # gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
			skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      skip_upload_metadata: true
    )
  end

  desc 'Deployar bundle a producción'
  lane :main do
    # gradle(task: 'clean assembleRelease')
    # crashlytics
    # gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      skip_upload_metadata: true
    )
  end
end
